-------------------------------------------------
-- Table to store EMPLOYEE records

CREATE TABLE EMPLOYEES 
(
  ID VARCHAR2(64) NOT NULL 
, FIRST_NAME VARCHAR2(32) NOT NULL 
, LAST_NAME VARCHAR2(32)
, EMAIL VARCHAR2(64) NOT NULL 
, PHONE VARCHAR2(16)
, BIRTH_DATE DATE 
, TITLE VARCHAR2(64) NOT NULL 
, DEPARTMENT NUMBER(8) NOT NULL
, CONSTRAINT EMPLOYEES_PK PRIMARY KEY 
  (
    ID 
  , EMAIL 
  )
  ENABLE 
);